/*
 * user_diskio_sd.h
 *
 *  Created on: Feb 28, 2025
 *      Author: arigu
 */

#ifndef INC_USER_DISKIO_SDMMC_H_
#define INC_USER_DISKIO_SDMMC_H_

#include "integer.h" //from FatFs middleware library
#include "diskio.h" //from FatFs middleware library
#include "ff_gen_drv.h" //from FatFs middleware library
#include "user_diskio.h"

#ifdef SDMMC_INTERFACE

static volatile DSTATUS Stat = STA_NOINIT;
static volatile uint8_t readStatus = 0, writeStatus = 0;

#define SD_DEFAULT_BLOCK_SIZE 512
#define SD_TIMEOUT 1000

//we define these as inline because we don't want them to be actual function calls (they get "called" from the cubemx autogenerated user_diskio file)
//we define them as extern because they are defined in a separate .c file to user_diskio.c (which #includes this .h file)

extern DSTATUS USER_SDMMC_initialize (BYTE lun);
extern DSTATUS USER_SDMMC_status (BYTE lun);
extern DRESULT USER_SDMMC_read (BYTE lun, BYTE *buff, DWORD sector, UINT count);
#if _USE_WRITE == 1
  extern DRESULT USER_SDMMC_write (BYTE lun, const BYTE *buff, DWORD sector, UINT count);
#endif /* _USE_WRITE == 1 */
#if _USE_IOCTL == 1
  extern DRESULT USER_SDMMC_ioctl (BYTE lun, BYTE cmd, void *buff);
#endif /* _USE_IOCTL == 1 */



#endif /* INC_USER_DISKIO_SDMMC_H_ */

#endif
