name: Compile Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    type: [opened, synchronize, reopened]

jobs:
  compile_test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake make gcc-arm-none-eabi

    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build project
      working-directory: ./zeropilot3.5
      run: bash ./hwbuild.bash -c l552
