name: Linting test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libgtest-dev libgmock-dev clang-tidy g++ build-essential

    - name: Build Main 
      working-directory: ./zeropilot3.5
      run: |
        chmod +x hwbuild.bash
        ./hwbuild.bash -c l552
        # Assuming hwbuild.bash configures CMake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build tests
      working-directory: ./zeropilot3.5/tests
      run: |
        chmod +x testbuild.bash
        ./testbuild.bash -c l552
        # Same assumption for testbuild.bash

    - name: Run clang-tidy lint script
      working-directory: ./zeropilot3.5
      run: |
        chmod +x lint.bash
        ./lint.bash  