name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    type: [opened, synchronize, reopened]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev libgmock-dev

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build tests
      working-directory: ./zeropilot3.5/tests
      run: bash ./testbuild.bash -c l552
    
    - name: Run tests
      working-directory: ./zeropilot3.5/tests
      run: bash ./build/gtestzeropilot3.5
